#!/usr/bin/env python

import sys

from rqt_svo1.svo1 import Svo1
from rqt_gui.main import Main

plugin = 'rqt_svo1'
main = Main(filename=plugin)
sys.exit(main.main(sys.argv, standalone=plugin)) # , plugin_argument_provider=Svo1.add_arguments
